// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhbmlblpobgwmgcqvbxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoYm1sYmxwb2Jnd21nY3F2YnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDEzMzIsImV4cCI6MjA2NjI3NzMzMn0.rsa-VO133m_Gg1tTeOCkzwItw8AN7UoMlRaUMmOJTkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);